# 参考配置文件
user:
  # 企业微信应用的配置，仅需前4项，若第五项配置了仅在缓存图片未找到的情况下使用;配置参考http://note.youdao.com/s/HMiudGkb
  qywx:
    corpid: ''
    agentid: ''
    secret: ''
    touser: '@all'
themoviedb:
  token: # themoviedb的api令牌，用来推送的时候提供图片
  max_retry_count: 5 # api请求的最大重试次数
  retry_wait_time: 10 # api请求的重试等待时间 秒