name: Update DockerHub description

on:
  push:
    branches:
    - master
    paths:
    - 'DOCKERHUB.md'

jobs:
  update_docker_description:
    name: Update DockerHub description
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: DockerHub Description
      uses: peter-evans/dockerhub-description@v2.0.0
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKERHUB_REPOSITORY: silentzephyrus/xarr_notify
        README_FILEPATH: ./DOCKERHUB.md