name: Docker Image CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          # 使用Dockerfile构建镜像
          docker build --file build/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/xarr_notify:1.0.0 .
          # 推送镜像到镜像仓库
          docker push ${{ secrets.DOCKER_USERNAME }}/xarr_notify:1.0.0