name: Docker Image CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          # 指定自己的仓库地址
          docker_repo: docker.io/silentzephyrus
          # 指定镜像名称
          image_name: xarr_notify
          # 指定镜像标签
          tag: latest
        run: |
          docker version
          # 登录阿里云镜像仓库
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          # 使用Dockerfile构建镜像
          docker build -f build/Dockerfile -t $docker_repo/$image_name:$tag .
          # 推送镜像到镜像仓库
          docker push $docker_repo/$image_name:$tag
